config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  root 'customers#index'
  get '/customers/missing_email', to: 'customers#missing_email'
  get '/customers/alphabetized', to: 'customers#alphabetized'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_one_attached :image
    validates :full_name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
# app/controllers/customers_controller.rb
class CustomersController < ApplicationController
    def index
      @customers = Customer.all
    end

    def alphabetized
        @customers = Customer.order(:full_name)
      end

      def missing_email
        @customers = Customer.where(email_address: [nil, ''])
      end
      
      


  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
<div class="customer">
  <%= image_tag customer.image if customer.image.attached? %>
  <h2><%= customer.full_name %></h2>
  <p><strong>Phone:</strong> <%= customer.phone_number %></p>
  <p><strong>Email:</strong> <%= customer.email_address %></p>
  <p><strong>Notes:</strong> <%= customer.notes %></p>
</div>

app/views/customers/alphabetized.html.erb
<!-- app/views/customers/alphabetized.html.erb -->
<% @customers.each do |customer| %>
  <%= render partial: 'customer', locals: { customer: customer } %>
<% end %>

app/views/customers/index.html.erb
<!-- app/views/customers/index.html.erb -->
<% @customers.each do |customer| %>
  <%= render partial: 'customer', locals: { customer: customer } %>
  <!-- app/views/customers/index.html.erb -->
<%= link_to "Missing Email", customers_missing_email_path %>
<%= link_to "Alphabetized", customers_alphabetized_path %>

<% end %>

app/views/customers/missing_email.html.erb
<!-- app/views/customers/missing_email.html.erb -->
<% @customers.each do |customer| %>
  <%= render partial: 'customer', locals: { customer: customer } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrmProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag 'customers', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>